### PR TITLE
Update the NDK version to r13b

### PR DESCRIPTION
**Pull request by joshpeterson**
* Clang seems to be missing from r13b, so use GCC 4.9
* The standard library headers have a macro redefinition warning, so disable warnings as errors.

### CODE REVIEW

**Comment by bitter** [comment]
Switching to GCC is probably not a good idea. Instead try switching to a later version of Clang.

NDK rev 14 relnotes:
> GCC deprecation: This release ends active support for GCC. GCC is not removed from the NDK just yet, but will no longer receive backports. As some parts of gnustl are still incompatible with Clang, GCC won't be entirely removed until after libc++ has become stable enough to be the default.

**Review by bitter — CHANGES_REQUESTED** [review]
Switching to GCC is probably not a good idea. Instead try switching to a later version of Clang.

NDK rev 14 relnotes:
> GCC deprecation: This release ends active support for GCC. GCC is not removed from the NDK just yet, but will no longer receive backports. As some parts of gnustl are still incompatible with Clang, GCC won't be entirely removed until after libc++ has become stable enough to be the default.

**Comment by joshpeterson** [comment]
@bitter: I did not see any version of clang in the r13b NDK, which seems a bit odd based on that deprecation message you referenced. I'll look again though.

**Comment by Over17** [comment]
@joshpeterson just checked r13b on win, clang 3.8 is there
android-ndk-r13b\toolchains\llvm\prebuilt\windows-x86_64\lib64\clang\3.8

**Comment by joshpeterson** [comment]
I've switched this to use clang instead of GCC now, thanks to help from @bitter.

**Review by mrvoorhe — APPROVED** [review]

**Review by bitter — APPROVED** [review]

**Pull request merged**
